version: '3.8'

services:
  app:
    build: .
    container_name: cloud_project
    environment:
      SPRING.DATASOURCE.URL: jdbc:mysql://localhost:3307/cloud_db?createDatabaseIfNotExist=True}
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: YourNewPassword
    depends_on:
      - mysql
    ports:
      - "8088:8080"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
      restart_policy:
        condition: on-failure


  mysql:
    image: mysql:8.0
    container_name: cloudproject-mysql
    environment:
      MYSQL_ROOT_PASSWORD: YourNewPassword
      MYSQL_DATABASE: cloud_db
      MYSQL_USER: viccyn
      MYSQL_PASSWORD: YourNewPassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount the configuration file
    ports:
      - "9090:9090"  # Expose Prometheus UI
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'  # Point to the config file

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana


volumes:
  mysql_data:
  grafana_data:


