spring.application.name=CloudProject
spring.datasource.url=jdbc:postgresql://cloudproject-postgres:5432/cloud_db
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Server Port
server.port=8088

#server.address=0.0.0.0
#management.endpoints.web.exposure.include=*






