spring.application.name=CloudProject
spring.datasource.url=jdbc:mysql://localhost/cloud_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.config.import=secret.properties
server.port=8088





