name: Deploy Dockerhub

on:
  push:
    branches:
      - in-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Restore Maven Package
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t vi108/cloudproject-app:latest .

      - name: Push Docker image to Docker Hub
        run: docker push vi108/cloudproject-app:latest

      - name: Connect to EC2 and Deploy
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          PEM_KEY: ${{ secrets.PEM_KEY }}  # This should correspond to the key stored in your secrets
        run: |
          # Write the PEM key to a file
          echo "${{ secrets.PEM_KEY }}" > cloudkeypair.pem  # Use the correct file name
          chmod 400 cloudkeypair.pem  # Set permissions for the key
          
          # SSH into the EC2 instance and deploy the application
          ssh -o StrictHostKeyChecking=no -i cloudkeypair.pem ubuntu@$EC2_PUBLIC_IP << 'EOF'
          # Update package lists
          sudo apt-get update
          
          # Check and install Docker and Docker Compose if not present
          if ! command -v docker &> /dev/null; then
              echo "Docker not found, installing..."
              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update
              sudo apt-get install -y docker-ce
              sudo systemctl start docker
              sudo systemctl enable docker
          else
              echo "Docker is already installed."
          fi
          
          # Check and install Docker Compose if not present
          if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose not found, installing..."
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
          else
              echo "Docker Compose is already installed."
          fi
          
          # Change directory to your project
         cd /home/ubuntu/CloudProject


          # Run Docker Compose
          sudo docker-compose up -d
          EOF
